/**
 * `Env` itself is generated by `wrangler types` (worker-configuration.d.ts) from wrangler.jsonc.
 * Secrets aren't in the config, so they're declared here as an augmentation.
 * Set them with `wrangler secret put <NAME>` (prod) or in `.dev.vars` (local).
 */
declare global {
  interface Env {
    /** Required header value for POST /refresh */
    REFRESH_SECRET?: string;
    /** Optional CoinGecko demo API key */
    COINGECKO_API_KEY?: string;
  }
}
export {};
